Estudiantes={
    'Estudiantes':{
        'Nombre':'TEXT',
        'Apellido':'TEXT',
        'DNI':'','INTEGER'
        'Fecha_de_nacimiento':'TEXT',
        'Programa_de_estudio':'TEXT',
        'Correo_Electronico':'TEXT'
        }
}